### ISSUE TITLE
Add option for more than 3 udhcpc retries when ssh unlocking boot

### ISSUE THREAD

**Issue by mariaa144** [ne9z/dotfiles-flake#1]
For my setup more than 3 udhcpc retries were necessary before an IP could be established for ssh unlocking. Perhaps a per host setting would be helpful for folks with this issue.

See: https://github.com/openzfs/openzfs-docs/issues/419

**Comment by ne9z** [comment]
You can just set the value inside ``configuration.nix``.

**Comment by ne9z** [comment]
I've added a custom module template. You can write your own options based on that.
