### ISSUE TITLE
unable to get new modules working

### ISSUE THREAD

**Issue by senorsmile** [ne9z/dotfiles-flake#5]
I have created a simple sample module based on the my-config module: 

```
{ config, pkgs, lib, ... }:
let
  cfg = config.smileycfg.pkgs-cli;
  inherit (lib) types mkOption mkIf;
in {
  options.smileycfg.pkgs-cli = {
    enable = mkOption {
      description = "Enable pkgs-cli?";
      type = types.bool;
      default = false;
    };
  };
  config = mkIf config.smileycfg.pkgs-cli.enable {
    environment.systemPackages = with pkgs; [
      htop
    ];
  };
}
```

I added it to modules/default.nix and enabled it in hosts/exampleHost/default.nix
```
  smileycfg.pkgs-cli = {
    enable = true;
  };
```

When I rebuild, it seems to run fine but doesn't add anything.  I've tried adding other things like services and nothing I add gets enabled.  I assume I've just missed something.

**Comment by ne9z** [comment]
Easy solution: put all your config under the `my-config` namespace and it will work.

Details: you need to recursively add `smileycfg` in flakes for it to work.  A simple grep shows where `my-config` is mentioned in the repo.
```
[:~/dotfiles-flake]$ git ls-files -z | xargs -0I'{}' grep -H my-config '{}'
configuration.nix:{ my-config, zfs-root, inputs, pkgs, lib, ... }: {
configuration.nix:  inherit my-config zfs-root;
flake.nix:      mkHost = { my-config, zfs-root, pkgs, system, ... }:
flake.nix:              inherit my-config zfs-root inputs pkgs lib;
hosts/exampleHost/default.nix:  my-config = {
modules/default.nix:  imports = [ ./boot ./fileSystems ./networking ./my-config ];
```
That means you need to mention it in `flakes.nix` and `configuration.nix` in the exact same spot where `my-config` was mentioned.

**Comment by senorsmile** [comment]
I figured this out just before I got notified of your response!  I didn't
see the mention of that but was able to trace out how the my-config even
worked and noticed that they needed to be brought into scope.

Thanks for the help and the great repo.

**Comment by ne9z** [comment]
Tip: you can shorten `config = mkIf config.smileycfg.pkgs-cli.enable{}` to just `config = mkIf cfg.enable {}` as you have set the `cfg` variable above.

**Comment by senorsmile** [comment]
Thanks, I hadn't noticed that.  
Only tangentially related, basic configuration in hosts/exampleHost/default.nix doesn't seem to work; it seems to be silently ignored.   I assumed I'd need to put it in a config block, but that is also silently ignored.

**Comment by ne9z** [comment]
They do work, or else the computer that I am currently using would not
even boot.  In any case, you can check whether the config works or not
by using nix repl command.

Run "nix repl", then load flake with ":lf .", assuming you are at the
root of the repo.  First, confirm that "zfs-root" scope exists.

nix-repl> nixosConfigurations.qinghe.config.zfs-root
{ boot = { ... }; fileSystems = { ... }; networking = { ... }; per-user = { ... }; }

Next, check an option, for example, host name.

nix-repl> nixosConfigurations.qinghe.config.zfs-root.networking.hostName
"qinghe"

Then, check the official NixOS option of host name.

nix-repl> nixosConfigurations.qinghe.config.networking.hostName
"qinghe"

They are the same, so it is working.

**Comment by senorsmile** [comment]
All config from modules work fine.  Let me clarify. 

Rather than using a config from a module, I want to include some config directly in the hosts/exampleHost/default.nix, so for example: 
```
  config = {
    environment.systemPackages = with pkgs; [
      clamav
    ];
  };
```
This just gets ignored, and clamav is not installed.

**Comment by ne9z** [comment]
You can do that, but it would require some changes to "flakes.nix" and
wipe-out "configuration.nix" to avoid any conflicting definitions.  Or
you can just write another option in "smileycfg" and enable it here.

I can post instructions if you still want to do that.

**Comment by ne9z** [comment]
Update: I was not able to directly add "config" directly in per-host
configuration.  It causes all kinds of conflicts with top-level
attrsets.


> You can do that, but it would require some changes to "flakes.nix" and
> wipe-out "configuration.nix" to avoid any conflicting definitions.  Or
> you can just write another option in "smileycfg" and enable it here.
>
> I can post instructions if you still want to do that.
>

**Comment by ne9z** [comment]
Another update.  It is possible, but you have to keep all the drop-in configuration in another separate file.  I have updated the template repo to accommodate this.

This is the new file, where all official NixOS options for only exampleHost should be kept: https://github.com/ne9z/dotfiles-flake/blob/openzfs-guide/hosts/exampleHost/configuration.nix
This file is optional, as the flake will only import it if this path exists.

All custom module options, i.e. `zfs-root` (necessary for boot), `my-config` and others are still kept in
https://github.com/ne9z/dotfiles-flake/blob/openzfs-guide/hosts/exampleHost/default.nix

There is still the main configuration.nix file, which contains configuration shared by all hosts.

These details can be inferred from the new flake.nix file, specifically the `modules` option.
https://github.com/ne9z/dotfiles-flake/blob/openzfs-guide/flake.nix#L16

**Comment by senorsmile** [comment]
This is much more elegant than what I hacked up!  

This is a cool idiom to ignore the else path:
```
else
                { }
```

Thanks for improving this and my nix knowledge.

**Comment by ne9z** [comment]
Belated update:  You can now put all options in one single file.  Not only that, you can also freely mix unstable packages with stable ones, or pin package version.  This is due to my newly gained understanding of how flake.nix should work.
